import type { Layout } from "./schema";
import { resolveLayerNames } from "./generateDtsi";

/**
 * The layer signal exists because ordinary host key events do not carry ZMK layer state. `9` typed
 * from base row 2 and `9` produced from a layer emit the same keycode; a base-only resolver can
 * therefore assign a layered event to the wrong Base position, while a code absent from Base is
 * left unattributed. The signal selects the matching per-layer metadata table on the host.
 *
 * `zmk_layer_state_changed` fires on every activation, so the firmware taps one spare key whenever
 * the highest active layer changes. One table, generated here, feeds both sides — the firmware
 * header the module compiles against and the metadata the daemon reads — because two
 * hand-maintained copies of the same mapping is a silent mis-attribution waiting to happen.
 */
export interface LayerSignal {
  /** The layer this code reports. Base clones report as the layer they clone. */
  layer: string;
  /** Index in the generated keymap, matching `#define LAYER_<name>`. */
  index: number;
  /** ZMK keycode name, as written in `layout.json5`. */
  code: string;
  linuxKeycode: number;
}

export interface LayerSignalLookup {
  (code: string): { linuxKeycode: number } | undefined;
}

/** A Base clone reports its source layer: `Base_BT2` is Base with different LED colours. */
function sourceLayerName(name: string): string {
  return /^Base_BT[1-4]$/.test(name) ? "Base" : name;
}

function everyBinding(layout: Layout): string[] {
  const bindings: string[] = [];
  for (const layer of layout.layers) {
    for (const side of [layer.keys.left, layer.keys.right, layer.keys.thumb_left, layer.keys.thumb_right]) {
      for (const row of side) bindings.push(...row);
    }
  }
  return bindings;
}

/**
 * Resolves the table, or throws with the reason. Every rule here exists because breaking it makes
 * the daemon mis-read data rather than fail: a code the keymap also types would make a real
 * keystroke look like a layer change, and a layer with no code would leave its keys attributed to
 * whichever layer was reported last.
 */
export function resolveLayerSignals(layout: Layout, lookup: LayerSignalLookup): LayerSignal[] {
  const config = layout.layerSignal;
  if (!config || !config.enabled) return [];

  const layerNames = resolveLayerNames(layout);
  const declared = new Set(layerNames.map(sourceLayerName));
  const signals: LayerSignal[] = [];
  const seenCodes = new Map<string, string>();

  for (const [layer, code] of Object.entries(config.codes)) {
    if (!declared.has(layer)) {
      throw new Error(`layerSignal.codes names layer '${layer}', which the keymap does not define`);
    }
    const previous = seenCodes.get(code);
    if (previous !== undefined) {
      throw new Error(
        `layerSignal.codes uses ${code} for both '${previous}' and '${layer}'; `
        + "one code cannot report two layers",
      );
    }
    seenCodes.set(code, layer);
  }

  // A code the keymap also types would be indistinguishable from a layer change on the host side.
  const typed = new Set(
    everyBinding(layout)
      .flatMap((binding) => binding.split(/\s+/).slice(1)),
  );
  for (const [code, layer] of seenCodes) {
    if (typed.has(code)) {
      throw new Error(
        `layerSignal.codes maps '${layer}' to ${code}, which the keymap also types; `
        + "a layer signal must be a key no layer produces",
      );
    }
  }

  for (const [index, name] of layerNames.entries()) {
    const layer = sourceLayerName(name);
    const code = config.codes[layer];
    if (code === undefined) {
      throw new Error(
        `layerSignal is enabled but layer '${layer}' has no code; every layer needs one, or the `
        + "keys typed on it are attributed to whichever layer was reported last",
      );
    }
    const resolved = lookup(code);
    if (!resolved) {
      throw new Error(`layerSignal.codes maps '${layer}' to unknown ZMK keycode ${code}`);
    }
    signals.push({ layer, index, code, linuxKeycode: resolved.linuxKeycode });
  }

  return signals;
}

/**
 * The header the ZMK module compiles against. It is an array indexed by layer index rather than a
 * lookup, so the firmware side is a single load with no search on a path that runs inside the
 * event manager.
 */
export function renderLayerSignalHeader(signals: LayerSignal[]): string {
  const lines = [
    "/*",
    " * Generated by `pnpm build` from config/layout.json5. Do not edit.",
    " *",
    " * One HID usage per layer index, tapped by zmk-modules/keylab-signal when that layer becomes",
    " * the highest active one. The same table is published in out/keymap-meta.json, which is what",
    " * the keylab daemon reads, so firmware and host cannot disagree about what a code means.",
    " */",
    "#pragma once",
    "",
    "#include <dt-bindings/zmk/keys.h>",
    "",
  ];

  if (signals.length === 0) {
    lines.push(
      "#define KEYLAB_LAYER_SIGNAL_ENABLED 0",
      "#define KEYLAB_LAYER_SIGNAL_LAYERS 0",
      "",
      "static const uint32_t keylab_layer_signal_usage[1] = {0};",
      "",
    );
    return lines.join("\n");
  }

  lines.push(
    "#define KEYLAB_LAYER_SIGNAL_ENABLED 1",
    `#define KEYLAB_LAYER_SIGNAL_LAYERS ${signals.length}`,
    "",
    "static const uint32_t keylab_layer_signal_usage[KEYLAB_LAYER_SIGNAL_LAYERS] = {",
  );
  for (const signal of signals) {
    lines.push(`    /* ${String(signal.index).padStart(2)} ${signal.layer} */ ${signal.code},`);
  }
  lines.push("};", "");
  return lines.join("\n");
}
