# ZMK Build Configuration for Glove80 with Per-Key RGB Support
# This file configures the build to use the community RGB fork

manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: moergo-sc
      url-base: https://github.com/moergo-sc
    - name: darknao
      url-base: https://github.com/darknao
  projects:
    - name: zmk
      remote: darknao
      revision: darknao/rgb-layer-24.12
      import:
        name-allowlist:
          - zephyr
          - zmk
    - name: glove80-zmk-config
      remote: moergo-sc
      revision: main
  self:
    path: config
  
build:
  settings:
    board: glove80_lh
    shield: ""
    snippet: ""
  boards:
    - glove80_lh
    - glove80_rh