/*
 * Tell the host which layer is active.
 *
 * The firmware has always known: `zmk_layer_state_changed` fires on every activation. The host
 * never did, because `9` typed from base row 2 and `9` produced from a layer emit the same
 * keycode — so everything typed from a layer is recorded as position-unattributed, and positional
 * telemetry means base-layer typing only.
 *
 * This taps one spare key whenever the *highest active* layer changes. Highest-active rather than
 * per-layer press and release because that is the layer a keypress actually resolves against, and
 * because every report then restates absolute state: a signal missed on the host costs one
 * transition, not an accounting error that persists until the next reboot.
 *
 * The tap goes through `zmk_keycode_state_changed`, exactly as `&kp` does, so it inherits the
 * whole existing path — endpoint selection, USB and BLE, HID indicators. The keys it taps are
 * ordinary HID keys the host will see; the table generator refuses any code the keymap itself
 * types, and the keylab daemon knows the table and never counts them.
 */

#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

#include <zmk/event_manager.h>
#include <zmk/events/keycode_state_changed.h>
#include <zmk/events/layer_state_changed.h>
#include <zmk/keymap.h>

/* Generated by `pnpm build` from config/layout.json5; see the module's CMakeLists.txt. */
#include <layer-signal.h>

LOG_MODULE_REGISTER(keylab_layer_signal, CONFIG_ZMK_LOG_LEVEL);

#if IS_ENABLED(CONFIG_KEYLAB_LAYER_SIGNAL) && KEYLAB_LAYER_SIGNAL_ENABLED

/* Nothing has been reported yet, so the first change always sends, including a change back to 0. */
static int reported_layer = -1;

static void report_active_layer(struct k_work *work) {
    ARG_UNUSED(work);

    const zmk_keymap_layer_index_t layer = zmk_keymap_highest_layer_active();
    if (layer >= KEYLAB_LAYER_SIGNAL_LAYERS) {
        /* A layer the generated table does not cover. Saying nothing is right: a wrong layer is
         * worse than no layer, because the host would attribute its keys to the wrong geometry. */
        LOG_WRN("layer %d is outside the signal table (%d entries)", layer,
                KEYLAB_LAYER_SIGNAL_LAYERS);
        return;
    }
    if ((int)layer == reported_layer) {
        /* Layers stack: activating one above the highest, or releasing one below it, changes the
         * state without changing which layer resolves a keypress. Those are not worth a report. */
        return;
    }

    reported_layer = layer;
    const uint32_t usage = keylab_layer_signal_usage[layer];
    const int64_t now = k_uptime_get();
    /* Press and release at the same instant: a tap, not a hold. A held key would autorepeat on the
     * host for as long as the layer stayed active. */
    raise_zmk_keycode_state_changed_from_encoded(usage, true, now);
    raise_zmk_keycode_state_changed_from_encoded(usage, false, now);
}

static K_WORK_DEFINE(report_work, report_active_layer);

static int layer_signal_listener(const zmk_event_t *eh) {
    ARG_UNUSED(eh);
    /* Off the event manager's own call stack. The handler raises another event, and the layer it
     * has to read is `zmk_keymap_highest_layer_active()` once the keymap has finished applying
     * this change — not the layer named in the event that woke it. */
    k_work_submit(&report_work);
    return ZMK_EV_EVENT_BUBBLE;
}

ZMK_LISTENER(keylab_layer_signal, layer_signal_listener);
ZMK_SUBSCRIPTION(keylab_layer_signal, zmk_layer_state_changed);

#endif /* CONFIG_KEYLAB_LAYER_SIGNAL && KEYLAB_LAYER_SIGNAL_ENABLED */
